# Generated by Django 3.2.8 on 2022-01-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_product_productsold_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
    ]
